<?php

if ( !defined( 'ABSPATH' ) )
	exit;

add_action( 'admin_menu', function() {
	if ( !current_user_can( 'administrator' ) )
		return;
	$page_title = 'KGR Polls';
	$menu_title = 'KGR Polls';
	$menu_slug = KGR_POLLS_KEY;
	$function = 'kgr_polls_settings';
	add_submenu_page( 'options-general.php', $page_title, $menu_title, 'administrator', $menu_slug, $function );
} );

function kgr_polls_settings() {
	if ( !current_user_can( 'administrator' ) )
		return;
	if ( array_key_exists( 'action', $_GET ) ) {
		kgr_polls_settings_action();
		return;
	}
	echo '<div class="wrap">' . "\n";
	echo sprintf( '<h1>%s</h1>', esc_html( 'KGR Polls' ) ) . "\n";
	echo '<hr class="wp-header-end" />' . "\n";
	kgr_polls_settings_notice( 'info', 'info', esc_html( 'Do not leave empty text fields.' ) );
	echo '<form method="post" action="options.php" class="kgr-polls-control-container">' . "\n";
	settings_fields( KGR_POLLS_KEY );
	do_settings_sections( KGR_POLLS_KEY );
	echo '<p class="submit">' . "\n";
	submit_button( 'save', 'primary', 'submit', FALSE );
	echo sprintf( '<button type="button" class="button kgr-polls-control-add" style="float: right;">%s</button>', 'add' ) . "\n";
	echo '</p>' . "\n";
	echo '</form>' . "\n";
	echo sprintf( '<h2>%s</h2>', esc_html( 'uninstall' ) ) . "\n";
	echo sprintf( '<p>%s</p>', esc_html( 'Before uninstalling, you may want to delete data generated by the plugin.' ) ) . "\n";
	echo '<table class="form-table">' . "\n";
	echo '<tbody>' . "\n";
	echo '<tr>' . "\n";
	echo sprintf( '<th scope="row">%s</th>', esc_html( 'option' ) ) . "\n";
	echo '<td>' . "\n";
	$action = 'delete-option';
	echo sprintf( '<a href="%s&action=%s&nonce=%s" class="button" onclick="return confirm( this.innerHTML );">%s</a>',
		menu_page_url( KGR_POLLS_KEY, FALSE ),
		$action,
		wp_create_nonce( KGR_POLLS_KEY . '-' . $action ),
		esc_html( 'delete' )
	) . "\n";
	echo sprintf( '<p class="description">%s</p>', esc_html( 'delete all polls' ) ) . "\n";
	echo '</td>' . "\n";
	echo '</tr>' . "\n";
	echo '<tr>' . "\n";
	echo sprintf( '<th scope="row">%s</th>', esc_html( 'user meta' ) ) . "\n";
	echo '<td>' . "\n";
	$action = 'delete-user-meta';
	echo sprintf( '<a href="%s&action=%s&nonce=%s" class="button" onclick="return confirm( this.innerHTML );">%s</a>',
		menu_page_url( KGR_POLLS_KEY, FALSE ),
		$action,
		wp_create_nonce( KGR_POLLS_KEY . '-' . $action ),
		esc_html( 'delete' )
	) . "\n";
	echo sprintf( '<p class="description">%s</p>', esc_html( 'delete all votes' ) ) . "\n";
	echo '</td>' . "\n";
	echo '</tr>' . "\n";
	echo '</tbody>' . "\n";
	echo '</table>' . "\n";
	echo '</div>' . "\n";
}

function kgr_polls_settings_action() {
	echo '<div class="wrap">' . "\n";
	echo sprintf( '<h1 class="wp-heading-inline">%s</h1>', esc_html( 'KGR Polls' ) ) . "\n";
	echo sprintf( '<a href="%s" class="page-title-action">%s</a>', menu_page_url( KGR_POLLS_KEY, FALSE ), esc_html( 'back' ) ) . "\n";
	echo '<hr class="wp-header-end" />' . "\n";
	if ( wp_verify_nonce( $_GET['nonce'], KGR_POLLS_KEY . '-' . $_GET['action'] ) ) {
		switch ( $_GET['action'] ) {
			case 'delete-option':
				delete_option( KGR_POLLS_KEY );
				kgr_polls_settings_notice( 'success', 'yes', esc_html( 'option deleted' ) );
				break;
			case 'delete-user-meta':
				$users = array_map( 'intval', get_users( [
					'meta_key' => KGR_POLLS_KEY,
					'fields' => 'ids',
				] ) );
				foreach ( $users as $user )
					delete_user_meta( $user, KGR_POLLS_KEY );
				kgr_polls_settings_notice( 'success', 'yes', esc_html( 'user meta deleted' ) );
				break;
		}
	} else {
		kgr_polls_settings_notice( 'error', 'no', esc_html( 'invalid nonce' ) );
	}
	echo '</div>' . "\n";
}

function kgr_polls_settings_notice( string $class, string $dashicon, string $message ) {
	echo sprintf( '<div class="notice notice-%s">', $class ) . "\n";
	echo sprintf( '<p class="dashicons-before dashicons-%s">%s</p>', $dashicon, $message ) . "\n";
	echo '</div>' . "\n";
}

add_action( 'admin_enqueue_scripts', function( string $hook ) {
	if ( $hook !== sprintf( 'settings_page_%s', KGR_POLLS_KEY ) )
		return;
	wp_enqueue_style( 'kgr-polls-progress', KGR_POLLS_URL . 'progress.css', [], NULL );
	wp_enqueue_script( 'kgr-polls-control', KGR_POLLS_URL . 'control.js', [ 'jquery' ], NULL );
} );
